#pragma once
#include "cmmn.h"
#include "surface.h"
#include "camera.h"
#include "texture.h"

namespace plu {
	// implements a multithreaded, tiled renderer with jittered multisample AA
	struct renderer {
	
		const uvec2 tile_size;
		shared_ptr<surface> scene;
		camera cam;

		renderer(shared_ptr<surface> S, const camera& C, uvec2 tile_size)
			: scene(S), cam(C), tile_size(tile_size) 
		{}

		// basically calls ray_color for the ray generated by cam for each pixel in target and stores the result color there
		void render(shared_ptr<texture2d> target) const;
		vec3 ray_color(const ray& r, size_t depth = 0) const;	
	private:
		void render_tile(shared_ptr<texture2d> target, vec2 inv_size, uvec2 pos) const;
	};
}
